### ISSUE TITLE
"require_mail_server" set to TRUE disabled mail server by local binding

### ISSUE THREAD

**Issue by gitbock** [darkwizard242/cis_ubuntu_2004#14]
# SUMMARY

If variable `require_mail_server` is set to true one may expect that mail server function is preserved. Instead, if set to true, postfix binds only on localhost, which disables the mail server function for hosts in the network.

 # ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

## CONFIGURATION
n/a

## OS / ENVIRONMENT 
**Ansible control node:** 
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Ansible managed node, with postfix installed**
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

 # STEPS TO REPRODUCE

- install ubuntu
- install postfix
- configure postfix to accept mails from other hosts (=mailserver function)
- run playbook with variable require_mail_server = true
- postfix stops working in the network

 # EXPECTED RESULTS

by setting variable to true, I expect the binding of postfix service to keep on 0.0.0.0 instead of localhost.

 # ACTUAL RESULTS
bind to localhost only according to lineincfg module. --> Ansibile is doing fine. Variable setting is confusing though.

# Suggestion
binding to localhost should be done if variable set to false.
require_mail_server= TRUE --> keep binding at 0.0.0.0 (or whatever set in config)
require_mail_server= FALSE --> bind to localhost only

**Comment by darkwizard242** [comment]
@gitbock  - Ah I see. Actually task **2.1.15 | Ensure mail transfer agent is configured for local-only mode (Automated)** sets it to only `localhost` based on the **CIS Benchmark for Ubuntu 20.04 (v1.1.0)**, which is likely causing that issue. 
https://github.com/darkwizard242/cis_ubuntu_2004/blob/54e4ffb3f8b90c68b4a05638c1d8470e758dbcbd/tasks/section_02.yml#L337-L356

If `require_mail_server` is set to false, it shouldn't touch any of the postfix configuration (i.e. `/etc/postfix/main.cf`). Do you mind setting it to false and confirming on your side for me. The action for if set to `true` or `false` was upon my initial thoughts, but I understand now that it actually had an opposite affect. If you test with false and it doesn't bind postfix only to localhost and/or impact anything esle on your side. I can probably have the when condition logic changed for the task to only run when `require_mail_server` is set to false instead of true and have it eventually released with your PR.

**Comment by gitbock** [comment]
Hi @darkwizard242 
Thanks for investigating!
I overruled the variable in my playbook
```
ubuntu_2004_cis_require_mail_server: false 
# false = postfix will bind on 0.0.0.0 -> mail server stays reachable
```
and executed it.

It did not touch my postfix config. The config line is still commented and was not added (means activated by ansible)
```

#inet_interfaces = localhost
inet_protocols = ipv4
mynetworks = 127.0.0.0/8 [...]
```


Yes, what do you think about inverting the logic by
```
when:
 - not ubuntu_2004_cis_require_mail_server
 ````
and modifying the description about the variable. Like this, it should be fine :)

**Comment by darkwizard242** [comment]
@gitbock - Great, thanks for verifying that 👍🏼 

Yes, agreed that inverting the when condition in the task to have the following makes more sense:

```yaml
when:
 - not ubuntu_2004_cis_require_mail_server
```

I will merge your PR #13 , add the above discussed changes and release a new version for GitHub + Ansible Galaxy.

_________________________

re: **ipv6** - The reason I had it disabled by default was primarily due to **CIS Benchmark for Ubuntu Linux 20.04 LTS** itself. Since the default recommendation in the benchmark is to have it disabled, I didn't wanted to deviate from that for the sake of anyone that uses the role and prefers the role to be as relatively close to the actual benchmark as possible. 

Honestly speaking, I too am in the same boat as you and have to override ipv6 configuration (to keep it enabled, contrary to the benchmark recommendation) in multiple projects where we utilize this role to build out CIS benchmark based AWS AMI's.

**Comment by darkwizard242** [comment]
@gitbock - Done, I merge your PR #13  and also changed the when condition as we discussed above for **2.1.15** in #15. 

GitHub release version [3.0.0](https://github.com/darkwizard242/cis_ubuntu_2004/releases/tag/3.0.0) has been released. **3.0.0** is now available on Ansible Galaxy.

**Comment by gitbock** [comment]
Hi @darkwizard242 

IPv6: understood. Already was thinking of this 😉 

Thanks for considering my PR 👍

**Comment by darkwizard242** [comment]
Great. Thanks very much for the PR and changes discussed in this issue. Appreciate both your time and help 👍🏼 

_p.s. (feel free to close the issue if it's good with you)_
