### ISSUE TITLE
User Errors 

### ISSUE THREAD

**Issue by eljefe-3** [darkwizard242/cis_ubuntu_2004#3]
I am fairly new at using ansible.  I am really not certain what exactly I am doing wrong.  

I created a role using the ansible-galaxy init command - cis_ubuntu_2004 and copied all of the folders into the new role I had created.

I executed this command: sudo ansible-playbook -i hosts playbook_with_defaults.yml and have tried adding tags "level_1", but I continue to get errors.

TASK [cis_ubuntu_2004 : 1.1.1.1 | Ensure mounting of cramfs filesystems is disabled (Automated) | custom template] ***************
fatal: [192.168.1.203]: FAILED! => {"msg": "The conditional check 'ubuntu_2004_cis_section1' failed. The error was: error while evaluating conditional (ubuntu_2004_cis_section1): 'ubuntu_2004_cis_section1' is undefined\n\nThe error appears to be in '/etc/ansible/roles/cis_ubuntu_2004/tasks/section_01.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"1.1.1.1 | Ensure mounting of cramfs filesystems is disabled (Automated) | custom template\"\n      ^ here\n"}

Do you have any idea why I am getting these errors?

Thank you for your assistance.

**Comment by darkwizard242** [comment]
No worries @eljefe-3, happy to help.

**ERROR:**
The cause of task failure is:

```shell
error while evaluating conditional (ubuntu_2004_cis_section1): 'ubuntu_2004_cis_section1' is undefined
```


**EXPLANATION:**
Each of the tasks in the role have **when** conditions as well as **tags** associated. Purpose of this was to allow any users who utilize this role to be able to customize CIS sections and subsections based on their business needs.

If we look at the error, that means the task is failing because it cannot identify where the dependent when condition requirement is set., which in this case is `ubuntu_2004_cis_section1`.  Now, `ubuntu_2004_cis_section1` is a boolean ansible variable (i.e. true or false). 

- If variable is defined and declared as `true`, then the task runs. 
- If variable is defined and declared as `false`,  then the task skips.
- If variable is not defined or declared, then the task fails.

The code for the task 1.1.1.1 itself is in the below snippet:

https://github.com/darkwizard242/cis_ubuntu_2004/blob/aaccda1ce3c10e599a16d2d751741d0481441496/tasks/section_01.yml#L4-L27


The variable by default has been declared in the below snippet:

https://github.com/darkwizard242/cis_ubuntu_2004/blob/aaccda1ce3c10e599a16d2d751741d0481441496/defaults/main/main.yml#L7



**SUGGESTION:**
It might be highly possible that either the variables files originally located in [defaults/main](https://github.com/darkwizard242/cis_ubuntu_2004/tree/master/defaults/main) or just the variable itself might be missing in the location that you may have copied to, which from the error you shared looks like: `/etc/ansible/roles/cis_ubuntu_2004`

You can also do a quick check using the following command (and share output if possible):

```shell
sudo grep -irn "ubuntu_2004_cis_section1:" /etc/ansible/roles/cis_ubuntu_2004
```

**Comment by eljefe-3** [comment]
First off, thank you for your willingness to help.  As I previously
mentioned I am new to using Ansible, but here are the steps that I have
taken.

 Per the instructions, I ran the following command and it downloaded the
repo in /home/ubuntu/.ansible

ansible-galaxy install darkwizard242.cis_ubuntu_2004,master

I ran the /home/ubuntu/.ansible/roles/darkwizard242.cis_ubuntu_2004

ansible-playbook playbook_defauflt.yml --tags: "level_1" -i hosts

[image: image.png]

In order to get rid of the error I created a new role in
/etc/ansible/role/cis_ubuntu_2004.  I proceeded by deleting all the
files and folders and copied the entire directory previously cloned.

I executed the grep commanded listed above for each of the sections.
The output was true.  Although I did change the value from true to
false on section 1 to test, but continue to get errors.  Again, I know
it is probably a step I missed that is why I thought I show all the
steps.


Thanks,

Wilberto
